language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
  - CI=false npm run build
notifications:
  email:
    recipients:
      - jiazheliu107@gmail.com
    on_success: always
    on_failure: always  